# Diagnostics
- platform: wifi_signal
  name: "Atom WiFi Signal"
  update_interval: 60s

- platform: uptime
  name: "Atom Uptime"

# Battery Voltage Monitor
- platform: adc
  pin: GPIO36
  name: "Atom Lite Battery Voltage"
  update_interval: 5min
  attenuation: 12db
  accuracy_decimals: 2
  filters:
    - multiply: 2
    - lambda: |-
        if (x > 4.2) {
          return 4.2;
        } else if (x < 3.3) {
          return 3.3;
        } else {
          return x;
        }
  unit_of_measurement: "V"
  icon: "mdi:battery"
  device_class: voltage
  state_class: measurement

# BLE RSSI Sensors (Named and Generic)
- platform: ble_rssi
  mac_address: "A4:C1:38:DA:D9:27"
  name: "Govee H5075 D927 RSSI"

- platform: ble_rssi
  mac_address: "C8:30:38:36:61:72"
  name: "Govee H5105 6172 RSSI"

- platform: ble_rssi
  mac_address: "D3:30:38:36:70:58"
  name: "Govee H5105 7058 RSSI"

- platform: ble_rssi
  mac_address: "D1:06:03:46:6F:37"
  name: "Govee H618A 6F37 RSSI"

- platform: ble_rssi
  mac_address: "D1:C7:C1:46:5A:87"
  name: "Govee H618A 5A87 RSSI"

- platform: ble_rssi
  mac_address: "D9:34:38:39:25:78"
  name: "Govee H605C 2578 RSSI"

- platform: ble_rssi
  mac_address: "D0:C9:07:4B:BB:BC"
  name: "Govee H7106 BBBC RSSI"

- platform: ble_rssi
  mac_address: "98:17:3C:3D:25:BD"
  name: "Govee H7106 25BD RSSI"

- platform: ble_rssi
  mac_address: "B0:E9:FE:57:DD:F0"
  name: "SwitchBot DDF0 RSSI"

- platform: ble_rssi
  mac_address: "B0:E9:FE:57:E2:BB"
  name: "SwitchBot E2BB RSSI"

- platform: ble_rssi
  mac_address: "E8:08:7C:A2:94:A1"
  name: "Blind Tilt 94A1 RSSI"

- platform: ble_rssi
  mac_address: "98:3D:AE:09:3D:86"
  name: "ihoment H714E 3D86 RSSI"

- platform: ble_rssi
  mac_address: "C2:08:A4:63:9F:7E"
  name: "BLE C2:08:A4:63:9F:7E RSSI"

- platform: ble_rssi
  mac_address: "F0:B3:EC:75:48:A0"
  name: "BLE F0:B3:EC:75:48:A0 RSSI"

- platform: ble_rssi
  mac_address: "E8:8D:A6:D5:3D:DD"
  name: "BLE 2HAE7300437Q073 RSSI"

- platform: ble_rssi
  mac_address: "E8:8D:A6:D5:3E:9C"
  name: "BLE 2HAE7300438Q291 RSSI"

- platform: ble_rssi
  mac_address: "EE:2E:03:06:25:3F"
  name: "SwitchBot Bot 253F RSSI"

- platform: ble_rssi
  mac_address: "66:1E:87:02:1C:D1"
  name: "VEEPEAK RSSI"

- platform: ble_rssi
  mac_address: "45:4D:16:49:24:E9"
  name: "BLE 45:4D:16:49:24:E9 RSSI"

- platform: ble_rssi
  mac_address: "5B:F1:BE:5D:32:9E"
  name: "BLE 5B:F1:BE:5D:32:9E RSSI"

- platform: ble_rssi
  mac_address: "5E:82:56:6D:FA:FF"
  name: "BLE 5E:82:56:6D:FA:FF RSSI"

- platform: ble_rssi
  mac_address: "5F:09:D4:42:D3:31"
  name: "BLE 5F:09:D4:42:D3:31 RSSI"

- platform: ble_rssi
  mac_address: "7F:E7:2D:52:31:0A"
  name: "BLE 7F:E7:2D:52:31:0A RSSI"

- platform: ble_rssi
  mac_address: "70:2A:D5:74:86:3D"
  name: "BLE 70:2A:D5:74:86:3D RSSI"

- platform: ble_rssi
  mac_address: "75:E9:92:86:03:FF"
  name: "BLE 75:E9:92:86:03:FF RSSI"

- platform: ble_rssi
  mac_address: "C8:C6:F2:3D:C7:CE"
  name: "BLE C8:C6:F2:3D:C7:CE RSSI"

- platform: ble_rssi
  mac_address: "D5:53:76:7B:A8:67"
  name: "BLE D5:53:76:7B:A8:67 RSSI"

- platform: ble_rssi
  mac_address: "D8:42:60:4C:E8:FC"
  name: "BLE D8:42:60:4C:E8:FC RSSI"

- platform: ble_rssi
  mac_address: "E3:15:20:23:8C:27"
  name: "BLE E3:15:20:23:8C:27 RSSI"

- platform: ble_rssi
  mac_address: "E5:A6:38:91:78:41"
  name: "BLE E5:A6:38:91:78:41 RSSI"

- platform: ble_rssi
  mac_address: "C3:91:D1:9D:F9:FA"
  name: "vuart:ktunnel RSSI"

- platform: ble_rssi
  mac_address: "90:15:06:FA:DC:3A"
  name: "Device RSSI"

- platform: ble_rssi
  mac_address: "DB:8A:12:A0:AD:D0"
  name: "BLE DB:8A:12:A0:AD:D0 RSSI"

- platform: ble_rssi
  mac_address: "18:C2:3C:38:6E:25"
  name: "Aqara 0804 0DE RSSI"

- platform: ble_rssi
  mac_address: "4D:AC:A9:2F:2F:2D"
  name: "BLE 4D:AC:A9:2F:2F:2D RSSI"

- platform: ble_rssi
  mac_address: "4A:C6:F3:61:2A:C9"
  name: "BLE 4A:C6:F3:61:2A:C9 RSSI"

- platform: ble_rssi
  mac_address: "CA:F0:F4:F1:C1:26"
  name: "BLE CA:F0:F4:F1:C1:26 RSSI"

- platform: ble_rssi
  mac_address: "C1:A5:4B:F1:BA:C1"
  name: "BLE C1:A5:4B:F1:BA:C1 RSSI"

- platform: ble_rssi
  mac_address: "58:98:1B:17:C6:C7"
  name: "BLE 58:98:1B:17:C6:C7 RSSI"

- platform: ble_rssi
  mac_address: "CC:6E:A4:20:AD:07"
  name: "BLE CC:6E:A4:20:AD:07 RSSI"

# On Atom Lite
- platform: ble_rssi
  mac_address: "A4:C1:38:DA:D9:27"
  name: "Govee D927 RSSI Atom"

# On New ESP
- platform: ble_rssi
  mac_address: "A4:C1:38:DA:D9:27"
  name: "Govee D927 RSSI NewESP"
