service: automation.turn_off
target:
  entity_id:
    - automation.track_gpt_requests
    - automation.smart_dashboard_optimization_reminder
    - automation.run_kodi_ai_when_prompt_is_updated
    - automation.git_sync_failure_alert
    - automation.save_latest_email_content_to_files
    - automation.notify_if_git_sync_stale_2
    - automation.run_yaml_validation_log_result
    - automation.sync_orphaned_files_to_recovery
    - automation.add_task_from_dashboard
    - automation.log_esp_restart_reason
    - automation.send_gpt_prompt_from_direct_input
    - automation.run_yaml_validation_log_result_2
    - automation.add_to_do_via_dashboard
    - automation.save_latest_email_content_to_files_2
    - automation.alert_if_wsl_restart_marker_missing
    - automation.ensure_gpt_status_file_permissions
    - automation.enable_entities_dashboard
    - automation.disable_entities_dashboard
    - automation.re_ask_chatgpt
    - automation.notify_system_update_available
    - automation.backup_success_reminder
    - automation.notify_of_stale_updates
    - automation.notify_backup_created
    - automation.run_gpt_when_prompt_changes
    - automation.announce_gpt_reply
    - automation.push_gpt_reply_to_mobile
    - automation.remind_vpn_on_for_streaming
    - automation.auto_bedtime_scene
    - automation.kitchen_blinds_open_morning_gradual
    - automation.kitchen_blinds_close_evening_gradual
    - automation.kitchen_window_open_alert
    - automation.alexa_kitchen_afternoon_greeting
    - automation.gpt_conversational_text_trigger_shell
    - automation.run_nas_script_from_chatgpt_prompt
    - automation.mark_gpt_as_sent
    - automation.admin_gpt_mark_as_sent
    - automation.admin_gpt_reply_complete
    - automation.gpt_conversational_text_trigger
    - automation.alert_if_jit_plugin_goes_offline
    - automation.alert_if_wsl_restart_marker_missing_2
    - automation.disable_noisy_entity_logging
    - automation.send_home_assistant_startup_report
    - automation.react_to_gpt_context_change
    - automation.reload_automations_after_startup
    - automation.log_gpt_context_change
    - automation.kitchen_light_off
    - automation.kitchen_manual_off
    - automation.flight_alert_takeoff_or_landing
    - automation.door_open_alexa_lounge_weather_advisory
    - automation.teddy_belt_level_up
    - automation.add_karate_belt_badge
    - automation.automation_2
    - automation.zigbee_motion_light_control
    - automation.reset_media_player_volume_after_playback_2
    - automation.reset_media_player_volume_after_playback_3
    - automation.ha_control_evening_mode
    - automation.ha_control_rainy_weather_mode
    - automation.ha_control_when_home
    - automation.red_arrows_watch
    - automation.j_home
    - automation.s_home
    - automation.aircraft_noise_detection_lounge_vibration
    - automation.log_aircraft_entry
    - automation.sync_media_player_selector
    - automation.fix_sheet_timestamp
    - automation.office_light_on_when_occupied
    - automation.ads_b_feed_heartbeat
    - automation.log_ads_b_emergency
    - automation.flash_lamp_for_low_aircraft
    - automation.hall_light_on_when_all_others_are_off_at_night
    - automation.update_notion_icon_when_hall_light_turns_off
    - automation.office_light_on_when_occupied_2
    - automation.office_light_off_after_no_motion
    - automation.office_light_on_when_occupied_3
    - automation.office_light_off_after_no_motion_2
